import {
  SettingOutlined,
  AppstoreOutlined,
  ReconciliationOutlined,
  UserOutlined,
  EditOutlined,
  StockOutlined,
  CommentOutlined,
  BarsOutlined,
  StarOutlined,
  BranchesOutlined,
} from '@ant-design/icons';

import WebSunnyIcon from 'components/MorningHuddle/WebSunnyIcon';
import PeopleOutlineIcon from 'components/Supervisor/PeopleOutlineIcon';

export const MenuList = [
  {
    icon: <AppstoreOutlined />,
    path: '/dashboard',
    slug: 'dashboard',
    title: 'Dashboard',
    isParent: false,
    children: [],
    permission: 0,
  },
  {
    icon: <AppstoreOutlined />,
    path: '/receptionist-dashboard',
    slug: 'receptionist-dashboard',
    title: 'Receptionist Dashboard',
    isParent: false,
    children: [],
    permission: 0,
  },
  {
    icon: <CommentOutlined />,
    path: '/conversation',
    slug: 'conversation',
    title: 'Conversation',
    isParent: false,
    children: [],
    permission: 8,
  },
  {
    icon: <ReconciliationOutlined />,
    path: '',
    slug: 'reports',
    title: 'Reports',
    isParent: true,
    permission: 11,
    children: [
      {
        title: 'Report Overview',
        slug: 'reports-overview',
        path: '/reports/reports-overview',
      },
      {
        title: 'Provider Analytics',
        slug: 'provider-analytics',
        path: '/reports/provider-analytics',
      },
      {
        title: 'Location Analytics',
        slug: 'location-analytics',
        path: '/reports/location-analytics',
      },
    ],
  },
  {
    icon: <EditOutlined />,
    path: '/online-booking/notification',
    slug: 'online-booking',
    title: 'Online Booking',
    isParent: false,
    children: [],
    permission: 4,
  },
  {
    icon: <BarsOutlined />,
    path: '/tasks',
    slug: 'tasks',
    title: 'Tasks',
    isParent: false,
    children: [],
    permission: 0,
  },
  {
    icon: <StarOutlined />,
    path: '',
    slug: 'review',
    title: 'Reviews',
    isParent: true,
    children: [],
    permission: 0,
    children: [
      {
        title: 'Reviews Received',
        slug: 'reviews-received',
        path: '/review/reviews-received',
      },
      {
        title: 'Needs Response',
        slug: 'needs-response',
        path: '/review/needs-response',
      },
      {
        title: 'Insights',
        slug: 'insights',
        path: '/review/insights',
      },
    ],
  },
  {
    icon: <WebSunnyIcon />,
    path: '/morninghuddle',
    slug: 'morninghuddle',
    title: 'Morning Huddle',
    isParent: false,
    children: [],
    permission: 0,
  },
  {
    icon: <PeopleOutlineIcon />,
    path: '/supervisor',
    slug: 'supervisor',
    title: 'Supervisor',
    isParent: false,
    children: [],
    permission: 0,
  },
  {
    icon: <StockOutlined />,
    path: '/pipeline',
    slug: 'pipeline',
    title: 'Pipeline',
    isParent: false,
    children: [],
    permission: 7,
  },
  {
    icon: <BranchesOutlined />,
    path: '/triggers',
    slug: 'triggers',
    title: 'Triggers',
    isParent: false,
    children: [],
    permission: 7,
  },
  {
    icon: <SettingOutlined />,
    path: '/setting/practice',
    slug: 'setting',
    title: 'Setting',
    isParent: false,
    children: [],
    permission: 12,
  },
  {
    icon: <UserOutlined />,
    path: '/profile',
    slug: 'profile',
    title: 'Profile',
    isParent: false,
    children: [],
    permission: 0,

  },
  
];

