import { RouteModel } from 'types';
import {
  ChatPage,
  DashboardPage,
  EmailSignaturePage,
  IntegrationsPage,
  LoginPage,
  ForgetPassPage,
  SetNewPassPage,
  OnlineBookingPage,
  PhoneNumberPage,
  PracticePage,
  RegisterPage,
  ReportsOverviewPage,
  TeamManagementPage,
  ProfilePage,
  ProviderAnalyticsPage,
  LocationAnalyticsPage,
  OnlineBookingNotificationPage,
  OnlineBookingNewPage,
  OnlineBookingCustomizationPage,
  OnlineBookingCalendarPage,
  OnlineBookingWidgetsPage,
  PipelinePage,
  ConversationPage,
  NeedsResponse,
  ReviewsReceived,
  Tasks,
  MorningHuddlePage,
  SupervisorPage,
  TriggersPage,
  TriggersDetailsPage,
  ReceptionistDashboardPage,
} from 'pages';

const ROUTES: RouteModel[] = [
  {
    path: '/auth/login',
    slug: 'login',
    exact: true,
    authorized: false,
    component: LoginPage,
    permission: 0,
  },
  {
    path: '/auth/forget-password',
    slug: 'forget-password',
    exact: true,
    authorized: false,
    component: ForgetPassPage,
    permission: 0,
  },
  {
    path: '/auth/set-new-password',
    slug: 'set-new-password',
    exact: true,
    authorized: false,
    component: SetNewPassPage,
    permission: 0,
  },
  {
    path: '/auth/register',
    slug: 'register',
    exact: true,
    authorized: false,
    component: RegisterPage,
    permission: 0,
  },
  {
    path: '/dashboard',
    slug: 'dashboard',
    exact: true,
    authorized: true,
    component: DashboardPage,
    permission: 0,
  },
  {
    path: '/receptionist-dashboard',
    slug: 'receptionist-dashboard',
    exact: true,
    authorized: true,
    component: ReceptionistDashboardPage,
    permission: 0,
  },
  {
    path: '/reports/reports-overview',
    slug: 'reports-overview',
    exact: true,
    authorized: true,
    component: ReportsOverviewPage,
    permission: 11,
  },
  {
    path: '/reports/provider-analytics',
    slug: 'provider-analytics',
    exact: true,
    authorized: true,
    component: ProviderAnalyticsPage,
    permission: 11,
  },
  {
    path: '/reports/location-analytics',
    slug: 'location-analytics',
    exact: true,
    authorized: true,
    component: LocationAnalyticsPage,
    permission: 11,
  },
  {
    path: '/pipeline',
    slug: 'pipeline',
    exact: true,
    authorized: true,
    component: PipelinePage,
    permission: 7,
  },
  {
    path: '/setting/chat',
    slug: 'chat',
    exact: true,
    authorized: true,
    component: ChatPage,
    permission: 12,
  },
  {
    path: '/setting/email-signature',
    slug: 'email-signature',
    exact: true,
    authorized: true,
    component: EmailSignaturePage,
    permission: 12,
  },
  {
    path: '/setting/integrations',
    slug: 'integrations',
    exact: true,
    authorized: true,
    component: IntegrationsPage,
    permission: 12,
  },
  {
    path: '/setting/online-booking-setting',
    slug: 'online-booking-setting',
    exact: true,
    authorized: true,
    component: OnlineBookingPage,
    permission: 12,
  },
  {
    path: '/setting/phone-number',
    slug: 'phone-number',
    exact: true,
    authorized: true,
    component: PhoneNumberPage,
    permission: 12,
  },
  {
    path: '/setting/practice',
    slug: 'practice',
    exact: true,
    authorized: true,
    component: PracticePage,
    permission: 12,
  },
  {
    path: '/setting/team-management',
    slug: 'team-management',
    exact: true,
    authorized: true,
    component: TeamManagementPage,
    permission: 12,
  },
  {
    path: '/profile',
    slug: 'profile',
    exact: true,
    authorized: true,
    component: ProfilePage,
    permission: 0,
  },
  {
    path: '/online-booking/notification',
    slug: 'notification',
    exact: true,
    authorized: true,
    component: OnlineBookingNotificationPage,
    permission: 4,
  },
  {
    path: '/online-booking/customization',
    slug: 'customization',
    exact: true,
    authorized: true,
    component: OnlineBookingCustomizationPage,
    permission: 4,
  },
  {
    path: '/online-booking/add-new-booking',
    slug: 'add-new-booking',
    exact: true,
    authorized: true,
    component: OnlineBookingNewPage,
    permission: 4,
  },
  {
    path: '/online-booking/calendar',
    slug: 'online-booking-calendar',
    exact: true,
    authorized: true,
    component: OnlineBookingCalendarPage,
    permission: 4,
  },
  {
    path: '/online-booking/widgets',
    slug: 'online-booking-widgets',
    exact: true,
    authorized: true,
    component: OnlineBookingWidgetsPage,
    permission: 4,
  },
  {
    path: '/conversation',
    slug: 'conversation',
    exact: true,
    authorized: true,
    component: ConversationPage,
    permission: 8,
  },
  {
    path: '/tasks',
    slug: 'tasks',
    exact: true,
    authorized: true,
    component: Tasks,
    permission: 4,
  },
  {
    path: '/review/reviews-received',
    slug: 'reviews-received',
    exact: true,
    authorized: true,
    component: ReviewsReceived,
    permission: 4,
  },
  {
    path: '/review/needs-response',
    slug: 'reports-overview',
    exact: true,
    authorized: true,
    component: NeedsResponse,
    permission: 11,
  },
  {
    path: '/review/insights',
    slug: 'insights',
    exact: true,
    authorized: true,
    component: ReviewsReceived,
    permission: 11,
  },
  {
    path: '/morninghuddle',
    slug: 'morninghuddle',
    exact: true,
    authorized: true,
    component: MorningHuddlePage,
    permission: 8,
  },
  {
    path: '/supervisor',
    slug: 'supervisor',
    exact: true,
    authorized: true,
    component: SupervisorPage,
    permission: 8,
  },
  {
    path: '/triggers',
    slug: 'triggers',
    exact: true,
    authorized: true,
    component: TriggersPage,
    permission: 8,
  },
  {
    path: '/triggers-details',
    slug: 'triggers-details',
    exact: true,
    authorized: true,
    component: TriggersDetailsPage,
    permission: 8,
  },
];

export default ROUTES;
